### PR TITLE
creating BasePage abstract class and designated folder - pages

### PR DESCRIPTION
**Pull request by Straumleaf**
Antony kindly check and merge my file

### CODE REVIEW

**Comment by Straumleaf** [comment]
Antony kindly check my file and merge accordingly. )

**Review by tjay79 — APPROVED** [review]
Great job, will merge now!!

**Comment by olDi1211** [comment]
Why only Anthony, why not me?????:((((((

**Comment by Straumleaf** [comment]
I don't want to bother you much especially with such tiny thing.

**Pull request merged**
